### ISSUE TITLE
Style the calculator

### ISSUE THREAD

**Issue by sarahxoxo** [sarahxoxo/calculator-style-hacktober#1]
Get started by creating css file and adding your custom style for the calculator

**Comment by mankutila** [comment]
I'll try to help you with it)

**Comment by error13** [comment]
would like to do a style sheet

**Comment by sarahxoxo** [comment]
nice to hear that!

**Comment by jgrrdnd** [comment]
Hi, i made neon style #37

**Comment by AdamTheWizard** [comment]
Hey, Sarah! I know this is the wrong place for a question but this site is ridiculously difficult to navigate for a beginner aha. I am trying to style the calculator you made and follow the instructions but I'm so new to this I'm really not sure on the best process of creating a style where I can preview the changes and then get them on Github. If you have a moment, would you mind briefly explaining what steps you would take yourself if you had stumbled across this repo or even just point me in the right direction. It would be very much appreciated. Thaanks! :)

**Comment by sarahxoxo** [comment]
@AdamTheWizard Hi, I'm not sure what is your question.Do you mean you want to check what you've changed in your code or run the html file in local?

**Comment by AdamTheWizard** [comment]
Yeah, I needed to figure out how to run it locally but through the help of twitter, I have figured it out! thanks for your response though :)
