### ISSUE TITLE
🐛 Period button not working correctly

### ISSUE THREAD

**Issue by vimkat** [sarahxoxo/calculator-style-hacktober#32]
I just discovered that the calculator's period button is not working correctly.
Currently, the only way I can insert decimal numbers is using the percentage button (or divide by a multiple of 10).

Maybe I will look into this over the weekend or somebody else could fix it right away.

For reference (may be a browser-related issue):
I'm using Safari version 11.0 (13604.1.38.1.6) on macOS High Sierra.

**Comment by jgrrdnd** [comment]
i went ahead and worked on this issue. pr #37 

please review

**Comment by sarahxoxo** [comment]
It works!
Thanks for the contribution.
